data = {"Gas Boiler": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Biomass Boiler": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Oil Boiler": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Boiler": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Electrical Heater": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Air Source Compression Heat Pump": {"capacity": 8, "costs": 13, "compare": [8]},   # capacity*fixed_cost - [P_max]
        "Shallow geothermal compression heat pump": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max]
        "Heat pump": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Gas CHP": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Oil CHP": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Biomass CHP": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Cogeneration": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Flat plate solar collectors": {"eta": 5, "costs": 13, "compare": [5]},  # (1000W/m^2)*area*efficiency*fixed_cost - [efficiency]
        "Evacuated tube solar collectors": {"eta": 5, "costs": 13, "compare": [5]},  # (1000W/m^2)*area*efficiency*fixed_cost - [efficiency]
        "Air source compression chiller": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Shallow geothermal compression chiller": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [16]},  # (Tes_size/Tes_charge_discharge)*fixed_cost - [Tes_size]
        "DHW thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [16]},  # (Tes_size/Tes_charge_discharge)*fixed_cost - [Tes_size]
        "Air source gas absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Shallow geothermal gas absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Deep geothermal HEX": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Industrial waste heat HEX": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Waste heat – HEX": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Waste cooling heat exchanger": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Waste cooling – HEX": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "waste_heat_heat_pumps_temperature_group1": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Waste Heat Compression Heat Pump Low T": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "waste_heat_heat_pumps_temperature_group2": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Waste Heat Compression Heat Pump Medium T": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "waste_heat_heat_pumps_temperature_group3": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Waste Heat Compression Heat Pump High T": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Industrial waste heat ORC": {"capacity": 8, "costs": 13, "compare": [8, 5, 10]},  # capacity*fixed_cost - [P_max, efficiency, power_to_heat_ratio]
        "Deep geothermal ORC": {"capacity": 8, "costs": 13, "compare": [8, 5, 10]},  # capacity*fixed_cost - [P_max, efficiency, power_to_heat_ratio]
        "Gas ORC": {"capacity": 8, "costs": 13, "compare": [8, 5, 10]},  # capacity*fixed_cost - [P_max, efficiency, power_to_heat_ratio]
        "Biomass ORC": {"capacity": 8, "costs": 13, "compare": [8, 5, 10]},  # capacity*fixed_cost - [P_max, efficiency, power_to_heat_ratio]
        "Seasonal Solar Thermal": {"eta": 5, "costs": 13, "compare": [5]},  # (1000W/m^2)*area*efficiency*fixed_cost - [efficiency]
        "Seasonal waste heat heat pumps": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Waste heat absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8]},  # capacity*fixed_cost - [P_max]
        "Seasonal thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [16]},  # (Tes_size/Tes_charge_discharge)*fixed_cost - [Tes_size]
        "Air source gas absorption chiller": {"capacity": 8, "costs": 13, "compare": [8, 5]},  # capacity*fixed_cost - [P_max, efficiency]
        "Shallow geothermal Gas absorption chiller": {"capacity": 8, "costs": 13, "compare": [8, 5]}  # capacity*fixed_cost - [P_max, efficiency]
        }