data = {"Gas Boiler": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Biomass Boiler": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Oil Boiler": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Boiler": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Electrical Heater": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Air Source Compression Heat Pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Shallow geothermal compression heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Gas CHP": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Oil CHP": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Biomass CHP": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Cogeneration": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Flat plate solar collectors": {"eta": 5, "costs": 13, "area": 3, "compare": [8, 13]},
        "Evacuated tube solar collectors": {"eta": 5, "costs": 13, "area": 3, "compare": [8, 13]},
        "Air source compression chiller": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Shallow geothermal compression chiller": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [8, 13]},
        "DHW thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [8, 13]},
        "Air source gas absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Shallow geothermal gas absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Deep geothermal HEX": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Industrial waste heat HEX": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste heat – HEX": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste cooling heat exchanger": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste cooling – HEX": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "waste_heat_heat_pumps_temperature_group1": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste Heat Compression Heat Pump Low T": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "waste_heat_heat_pumps_temperature_group2": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste Heat Compression Heat Pump Medium T": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "waste_heat_heat_pumps_temperature_group3": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste Heat Compression Heat Pump High T": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Industrial waste heat ORC": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Deep geothermal ORC": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Gas ORC": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Biomass ORC": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Seasonal Solar Thermal": {"eta": 5, "costs": 13, "area": 3, "compare": [8, 13]},
        "Seasonal waste heat heat pumps": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Waste heat absorption heat pump": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Seasonal thermal energy storage": {"size": 16, "cost": 13, "charge": 19, "compare": [8, 13]},
        "Air source gas absorption chiller": {"capacity": 8, "costs": 13, "compare": [8, 13]},
        "Shallow geothermal Gas absorption chiller": {"capacity": 8, "costs": 13, "compare": [8, 13]}
        }