# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlanningAndSimulationModules
                                 A QGIS plugin
 Planning_And_Simulation_Modules
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-16
        copyright            : (C) 2019 by softeco
        email                : eglantina.metani@softeco.it   daniele.bonventre@softeco.it
        git sha              : $Format:%H$
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlanningAndSimulationModules class from file PlanningAndSimulationModules.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .planning_and_simulation_modules import PlanningAndSimulationModules
    return PlanningAndSimulationModules(iface)
